Replaced result_of with invoke_result_t.
KjellKod/g3log pull request #392
Opened 2020-12-06 05:32 UTC by Friendly0Fire

C++17 deprecates `std::result_of<T>` and C++20 completely removes it from the spec in favor of `std::invoke_result<T>`, preventing compilation of g3log if using C++20-level features.

This is the simplest fix which merely replaces all instances of the former with the latter, but it will break compilation on C++14 or older. It would also be possible to make an alias of these templates and use macro compile flags to preserve compatibility with C++14, but I wasn't sure if that would be necessary.

I also took the liberty to use the `*_t` declarations which are much less verbose.

2020-12-06 17:14 UTC, KjellKod commented
Thanks. Before I merge this I need to creat a branch and release for “last release with C++14 support”. 

On your end, please update the CI configuration to work with your changes. Once the tests are working I’ll review this PR

2020-12-14 04:01 UTC, Friendly0Fire commented
Any idea when this can be merged?

2020-12-14 14:53 UTC, KjellKod commented
Thanks for the reminder. I’ve planned to create the release w/tagging and review and this this PR this ongoing week

2020-12-14 19:52 UTC, KjellKod requested changes
Kick ass change. Just one tiny file removal and it should be good to go (pending my testing)

2020-12-14 19:52 UTC, KjellKod commented on .vscode/settings.json
> +{
please remove this file

2020-12-15 15:21 UTC, Friendly0Fire commented on .vscode/settings.json
> +{
Done!

2020-12-16 13:51 UTC, merged

2020-12-21 16:11 UTC, gir489 commented
I have confirmed this fixed #337.