SOName needs to be less volatile
KjellKod/g3log pull request #402
Opened 2021-04-04 07:00 UTC by Shachar

The SOName of the created library changes with every tiny change to the code. This makes the library impossible to package, as well as a host of other problems. This patch makes the SO name take only the major component of the version.

- [ ] **TDD** 

There is no new code or functionality.

- [ ] **Documentation**

This change applies only to the ABI. There is no change to the API.

**Cross-Platform Testing**
- [ ] Travis-CI (Linux, OSX) + AppVeyor-CI (Windows)\
- [ ] *Optional:* Local/VM testing: Windows
- [ ] *Optional:* Local/VM testing: OSX
- [ ] *Optional:* Local/VM testing: Linux

**Testing Advice**
```bash 
mkdir build; cd build; cmake -DADD_G3LOG_UNIT_TEST=ON ..
```

**Run Test Alternatives:** 
- Cross-Platform: `ctest`
- or `ctest -V` for verbose output
- Linux: `make test`

2021-04-05 03:13 UTC, KjellKod requested changes

2021-04-05 03:13 UTC, KjellKod commented on CMakeLists.txt
> +   SET(SOFT_VERSION ${MAJOR_VERSION}.${MINOR_VERSION}.${BUILD_NUMBER}-${VERSION-REMAINDER})
Did you mean `soversion`? AFAIK `SOFT_VERSION` is not a reserved keyword in cmake
https://cmake.org/cmake/help/latest/prop_tgt/SOVERSION.html#prop_tgt:SOVERSION

2021-04-07 13:59 UTC, Shachar commented
Revised based on discussion on #403.

2021-04-09 03:29 UTC, KjellKod approved these changes

2021-04-09 03:29 UTC, merged