Update loglevels.hpp
KjellKod/g3log pull request #496
Opened 2023-05-19 02:05 UTC by CryptoManiac

See #495 for details

Issue is not triggered if __cplusplus is less than 202002L on your system.

2023-05-19 18:54 UTC, KjellKod commented
@SzGaa  please review this.

2023-05-19 19:02 UTC, KjellKod commented
I think this is fine. Running tests now. `constexpr` vs const isn't really a huge win regardless outside of making it more up-to-date. I'm planning to merge this once it's all gone through CI

2023-05-19 19:03 UTC, KjellKod commented
Thank you @CryptoManiac for this insight and update

2023-05-19 19:06 UTC, KjellKod requested changes

2023-05-19 19:06 UTC, KjellKod commented on src/g3log/loglevels.hpp
> +const
please make this the same line as `LEVELS G3LOG_DEBUG{g3::kDebugValue, "DEBUG"},`

Ref how it was earlier https://github.com/KjellKod/g3log/commit/cc0fb7c1ea7d7cc2bc5d8766b18b190ba74b70f9

2023-05-20 06:12 UTC, CryptoManiac commented
> I think this is fine. Running tests now. `constexpr` vs const isn't really a huge win regardless outside of making it more up-to-date. I'm planning to merge this once it's all gone through CI

This testing doesn't have a lot of sense because `const` vs `constexpr` have fundamental differences which are nothing to do with either performance or being up to date. The `const` identifiers are variables. Read-only, yes, but still allocated as usual. The same can't be said about constexpr expressions, they only exist at compile-time and there is no such thing in the generated code. Therefore, there is a lot of limitations on what you can or can't do with them. For `constexpr` identifier any input data must be known at compile time, meaning that there is no way to allocate dynamic memory for them or whatever. They're good for switches and math equations or other things like that. You can use the result of constexpr expression as a template argument, for example, while the same can't be done with `const` identifiers.

2023-05-20 06:38 UTC, SzGaa commented
> The `const` identifiers are variables. Read-only, yes, but still allocated as usual. The same can't be said about constexpr expressions, they only exist at compile-time and there is no such thing in the generated code.

Compiler is not forced to use constexpr in compile context only (also not guaranteed that it will use that way even if could be possible), just allows it to be used in places where only compile time constants would be applicable.
Also constexpr implies constness.

[constexpr specifier](https://en.cppreference.com/w/cpp/language/constexpr)

2023-05-20 07:11 UTC, CryptoManiac commented
> Compiler is not forced to use constexpr in compile-time context only (also not guaranteed that it will use that way even if could be possible), just allows it to be used in places where only compile time constants would be applicable. 

It allows them to be used in places like that because it does provide a guarantee that the expression is deterministic and the required data is known at compile-time. Therefore it _may be_ evaluated in compile-time. Of course, for the sake of common sense, compiler won't actually evaluate expressions unless they're something very simple. But this has no visible side effects since the said limitations still stand. No heap allocations, no exceptions and only literal value types. It's also kind of understandable why `goto` is not supported, since though they're quite possible to implement, it would be really hard to actually do such a thing. 

> Also constexpr implies constness.

Well, Shakespeare was born in England, he wrote in english and spoke in english as well. Therefore, Shakespeare was english. Of course they are const since they're deterministic and their input data is const as well. :)

2023-05-20 13:14 UTC, KjellKod approved these changes

2023-05-20 13:16 UTC, merged